### ISSUE TITLE
有部分帖子无法打开，有报错信息

### ISSUE THREAD

**Issue by kokororin** [Jiny3213/vscode-tieba#9]
如：https://tieba.baidu.com/p/9352351912

报错信息：
```
mainThreadExtensionService.ts:79 TypeError: Cannot set properties of undefined (setting 'commentList')
	at c:\Users\XXX\.vscode\extensions\wister.vscode-tieba-0.1.5\out\api\index.js:114:40
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\XXX\.vscode\extensions\wister.vscode-tieba-0.1.5\out\api\index.js:5:58)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Jiny3213** [comment]
我用插件打开了这个帖子，没有遇到这个问题。你关闭重新打开看看？

**Comment by Jiny3213** [comment]
这个问题应该是【回复】找不到对应的【楼层】，推测是删楼之后，百度仍然返回了该楼的【回复】导致的

**Comment by kokororin** [comment]
很多帖子都会出现，能否优化一下呢

**Comment by Jiny3213** [comment]
可以，我排查一下

**Comment by Jiny3213** [comment]
0.1.6版本已修复

**Comment by kokororin** [comment]
此问题又出现了：

```
mainThreadExtensionService.ts:78 [wister.vscode-tieba]Cannot read properties of undefined (reading 'data')
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
mainThreadExtensionService.ts:79 TypeError: Cannot read properties of undefined (reading 'data')
    at c:\Users\xxx\.vscode\extensions\wister.vscode-tieba-0.1.7\out\api\index.js:171:36
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Jiny3213** [comment]
有没有复现帖子

**Comment by kokororin** [comment]
再次刷新又好了，没有复现
